// Code generated by tygo. DO NOT EDIT.
// ⚠ AUTO-GENERATED FROM internal/wire/types.go BY tygo. DO NOT EDIT.
// To change shape: edit Go source then `make codegen`.

//////////
// source: errors.go

/**
 * Error classification for wire.KindError envelopes (tether#63).
 * # The gap this closes
 * Before this file, a KindError envelope's Payload was a bare string — cc's
 * error text, or a hand-written sentence like "session owned by another
 * client". That carries a message but no VERDICT: the browser cannot tell
 * "this connection is permanently refused, stop retrying" from "this attempt
 * failed, try again" without pattern-matching the string, which is exactly the
 * kind of coupling this package exists to avoid (doc.go: "only types that
 * cross the wire belong here"). tether#52 made an unknown/unregistered
 * workspace fail closed — correctly — but the browser's reconnect ladder
 * (web/src/panes/chat/index.tsx) resets its attempt counter on every
 * SUCCESSFUL WebTransport handshake, and a refusal like this one arrives AFTER
 * the handshake succeeds (wts.Upgrade in wt_chat.go has already returned by
 * the time serveChat sends the error). So the counter never accumulates and
 * the ladder retries forever, once a second, against a workspace that will
 * never come back — an endless spinner where the daemon KNEW the retry was
 * pointless the whole time.
 * # Why disposition is its own wire field, not something the browser infers
 * The obvious alternative is: ship the code, let the browser decide which
 * codes are worth retrying. That puts the classification in TWO places that
 * must be kept in sync across a wire boundary and, worse, across a language
 * boundary — a Go const added here without a matching TypeScript case falls
 * back to "unhandled" silently, no compiler in either language catches the
 * gap, and the failure mode is the one this file exists to close (the daemon
 * KNOWS the answer and does not say it). Sending Terminal as a bool alongside
 * Code means the browser's ONE rule is "read the bit", never "recognize the
 * string" — a rule that is still correct for a code the frontend has never
 * heard of (see below), and one new terminal error case tomorrow needs a
 * change in exactly one place: this file.
 * # Why Terminal is derived from one table, not decided at each call site
 * A call site constructing a KindError envelope by hand can set Terminal to
 * whatever it wants, which means the true answer to "is unknown_workspace
 * terminal" is scattered across however many places build one — and a future
 * refusal added at a new call site is one copy-paste-and-forget away from
 * shipping with the wrong bit. NewErrorEnvelope is the only constructor this
 * package exposes for a KindError envelope, and it derives Terminal from
 * terminalCodes below, so the classification lives in exactly one place a
 * reviewer can read start to finish, and every caller gets it for free by
 * naming a code instead of a bool.
 * # Why an unclassified code defaults to retryable, not terminal
 * terminalCodes is asserted exhaustive over every ErrorCode this package
 * declares (errors_test.go's AST-based test parses the package's own source
 * and fails the build if a new const is added without an entry), so
 * "unclassified" should never happen for a code declared here. It CAN happen
 * for a code this build does not know about: an older frontend talking to a
 * newer daemon after a partial deploy, for instance. Defaulting a lookup miss
 * to false (retryable) means that mismatch degrades to the old
 * behaviour — reconnect and hope — rather than bricking a client that has
 * done nothing wrong. Defaulting to true would mean any code neither side
 * currently recognizes stops the browser retrying a connection that a fixed
 * build might have accepted, which is the more dangerous failure to be wrong
 * about: a stuck-retrying client wastes cycles, a client that gave up too
 * early loses a reconnect it needed.
 */
export type ErrorCode = string;
/**
 * ErrCodeUnknownWorkspace means the requested workspace id is not in this
 * daemon's registry (session/workspace.go resolveWorkspace). Terminal: the
 * registry will not gain that id by retrying the same connection.
 */
export const ErrCodeUnknownWorkspace: ErrorCode = "unknown_workspace";
/**
 * ErrCodeNoWorkspaceRegistry means a workspace id was requested but this
 * daemon has no registry to check it against (it failed to load at
 * startup). Kept distinct from ErrCodeUnknownWorkspace on purpose — see
 * resolveWorkspace's doc comment — because an operator chasing "workspace
 * was deleted" and one chasing "registry failed to load at startup" are
 * chasing two different bugs. Terminal for the same reason: a registry
 * that failed to load once does not load itself by being asked again.
 */
export const ErrCodeNoWorkspaceRegistry: ErrorCode = "no_workspace_registry";
/**
 * ErrCodeUnknownProvider means the requested agent provider name is not
 * registered (session/registry.go spawnEntry). Terminal: the set of
 * registered providers is fixed at daemon startup, so retrying the same
 * request cannot change the answer.
 */
export const ErrCodeUnknownProvider: ErrorCode = "unknown_provider";
/**
 * ErrCodeSessionOwned means this sid is already claimed by a different
 * client (tether#54's OwnedByOther / Entry.setOwner).
 * "Client" here is a DEVICE, not a tab: clientID comes from the login cookie
 * (internal/auth/middleware.go) and the SPA persists one per browser profile
 * in localStorage, so every tab of one browser shares it and admitChat lets
 * them all in. This refusal is therefore reached from a SECOND DEVICE, and
 * opening another tab is not a workaround for it.
 * Terminal for this connection: Entry.ownerClientID has one writer and is
 * never reset, so the other device closing its tab does not release the
 * session — retrying the same chat connection is refused for as long as the
 * entry lives. /wt/events attaches read-only instead.
 */
export const ErrCodeSessionOwned: ErrorCode = "session_owned_by_other";
/**
 * ErrCodeSpawnFailed means provider.Spawn itself returned an error
 * (session/registry.go spawnEntry) — e.g. the agent binary is missing or
 * failed to start. Retryable: nothing here is a property of the browser's
 * request, and a transient exec failure (or an operator fixing the
 * binary) can succeed on the very next attempt.
 */
export const ErrCodeSpawnFailed: ErrorCode = "spawn_failed";
/**
 * ErrCodeConnectionClosed means the browser's connection was cancelled
 * before the agent session confirmed itself (session/attach.go resolve).
 * Retryable: the daemon did nothing wrong and there is nothing to fix —
 * reconnecting is the entire remedy, and is exactly what a browser that is
 * still around will do on its own.
 */
export const ErrCodeConnectionClosed: ErrorCode = "connection_closed";
/**
 * ErrCodeSessionUnconfirmed means a freshly spawned agent exited before
 * emitting a session id, with no resume to fall back to (session/attach.go
 * resolve's `!resuming` branch). MUST stay retryable — Attach's own doc
 * comment (internal/session/attach.go) is explicit that recovering a
 * failed resume depends on the browser's ordinary reconnect landing on the
 * `--resume` path next time; marking this terminal would turn a
 * recoverable hiccup (a bad spawn, a transient cc crash) into a dead end
 * the ladder refuses to retry out of.
 */
export const ErrCodeSessionUnconfirmed: ErrorCode = "session_unconfirmed";
/**
 * ErrCodeAgent means the agent process itself reported an error
 * (agent.EventError — session/registry.go translateEvent). It is the agent
 * speaking, not the daemon refusing the connection, and that is the whole of
 * what it says.
 * It does NOT say the session survived, and until tether#80 this comment
 * claimed it did ("the session the browser is attached to is still alive and
 * usable"). That was wrong, and wrong in the direction that misleads: a
 * consumer reading it would present this error as a note about the current
 * turn on a healthy session. The emit sites span four materially different
 * situations that arrive on the wire indistinguishable:
 *   - session.error from opencode's event stream: a complaint about the turn;
 *     session alive, prompt delivered.
 *   - SendPrompt's busy branch, its resume-serve failure, and the two
 *     `opencode run` start failures: each emits and then returns nil, so the
 *     user's PROMPT WAS DROPPED, while the session stays alive.
 *   - watchServeExit: emits and then closes the event stream, so THE SESSION
 *     IS ALREADY GONE when this is read.
 *   - agent/claude_provider.go's ccSession.abandon: cc's stdout read ended in
 *     an error, so the subprocess is killed and the TURN DIED MID-ANSWER.
 * That last one also corrects this comment, not just extends it: tether#80
 * wrote "every emit site is in agent/opencode_provider.go (cc emits none at
 * all)" here, and tether#83's review found abandon. The claim travelled — the
 * same sentence had been copied into web/src/lib/store.ts — which is why it is
 * fixed at the source rather than only where it was read.
 * Anything that needs to distinguish those needs a new code, not a reading of
 * this one. web/src/lib/store.ts's agent_error branch is written to that
 * constraint: it shows who spoke and what they said, and asserts nothing about
 * the session or the prompt.
 * Retryable, and that verdict is unchanged and right at both ends of the
 * range: nothing here is a property of the browser's request, so a reconnect
 * is the correct response whether the agent merely complained or its serve
 * has exited.
 */
export const ErrCodeAgent: ErrorCode = "agent_error";
/**
 * ErrCodePromptUndelivered means the user's prompt did not reach any agent
 * and no further recovery is coming for it (session/attach.go reopen, on
 * every branch that gives up rather than the ones that hand the problem to
 * machinery which will retry).
 * Named for the prompt rather than for the session because the session
 * state differs across those branches while the user-visible fact does
 * not: the reopen budget may be spent, or a live replacement may have been
 * found and refused the prompt anyway. All of them mean the same thing to
 * the person who just pressed enter — those words are gone — and that is
 * what the message needs to say.
 * Retryable, and deliberately: the attachment was armed — either its session
 * confirmed, or it reused one that was live — so an ordinary reconnect lands
 * on the `--resume` path, which has its full fallback machinery behind it
 * for the case where the transcript turns out not to exist, and a fresh
 * attachment gets a fresh reopen budget. Marking it terminal would stop the
 * browser's ladder on the one failure a reconnect actually fixes.
 * "Armed" and not "confirmed": reopenSID has two arming sites of different
 * strength and session/attach.go is explicit that collapsing them is wrong
 * ("Do not collapse these two into 'armed ⟹ the transcript exists'"). The
 * reuse site observes only liveEntry, so this code can reach the browser
 * from an attachment whose session never emitted a session id. The verdict
 * is the same either way, which is exactly why it is worth stating the
 * weaker premise it actually rests on.
 * Not ErrCodeAgent, which would be the closest existing fit and is wrong
 * in the way that matters here: that code means the agent REPORTED
 * something about a turn it is still able to continue. On these branches
 * the agent said nothing at all — it died, or was never reachable — and
 * the connection is not usable until it is remade.
 */
export const ErrCodePromptUndelivered: ErrorCode = "prompt_undelivered";
/**
 * ErrorPayload is the Payload of a KindError Envelope once it carries a Code.
 * Message is unchanged from the pre-tether#63 behaviour (cc's error text, or a
 * hand-written sentence) and is human-readable but NOT parsed by the browser;
 * Code and Terminal are what the browser is meant to act on.
 */
export interface ErrorPayload {
  code: ErrorCode;
  message: string;
  terminal: boolean;
}

//////////
// source: format.go

/**
 * HashHex64 is the canonical wire format for SHA-256 fingerprints:
 * 64 lowercase hex characters, no separators, no prefix.
 * Browser parser regex: ^[0-9a-f]{64}$
 * Accepted:   "4c55656033cc29b05037294b2c1bdd2c294963b57b9238a2a758aec8d87eb288"
 * Rejected:   "4c:55:65:..." (colons), "4C55..." (uppercase), "0x4c55..." (prefix)
 * Both /cert-hash (DER) and /cert-hash-spki (SPKI) return values of this type.
 * Validated by wire-contract.spec.ts contract K.7.1 / D-22 §6 #1.
 */
export type HashHex64 = string;
/**
 * SessionID is the stable identifier for a cc-managed JSONL session,
 * as returned in the system/init stream-json event (D-05a §3).
 * Opaque string; format is cc-internal and subject to change.
 */
export type SessionID = string;

//////////
// source: types.go

/**
 * EnvelopeKind is the discriminator field on every wire envelope.
 * The browser dispatches on this value to route to the correct handler.
 * Additional kinds are added in s4+ as channels are implemented.
 */
export type EnvelopeKind = string;
export const KindMessage: EnvelopeKind = "message"; // assistant text / tool output (s4)
export const KindPermission: EnvelopeKind = "permission"; // PreToolUse callback (s5)
export const KindFenced: EnvelopeKind = "fenced"; // D-19 fenced-block structured output (s4)
export const KindError: EnvelopeKind = "error"; // daemon-side error surfaced to UI
export const KindResult: EnvelopeKind = "result"; // turn complete; payload is stop reason string
/**
 * Envelope is the top-level wrapper for all events sent over /wt/events
 * and /wt/chat. The Payload field carries kind-specific JSON (D-05a §3,
 * D-05b §3.1, D-19). Routing table per §10.B.4 is implemented in s4.
 */
export interface Envelope {
  kind: EnvelopeKind;
  sessionId?: SessionID;
  payload?: any;
}
/**
 * FencedBlockKind is the discriminator for D-19 fenced-block protocol.
 * v0.1 defines 5 kinds; more may be added in v1.0+.
 */
export type FencedBlockKind = string;
export const FencedBlockDag: FencedBlockKind = "dag";
export const FencedBlockForm: FencedBlockKind = "form";
export const FencedBlockCandidates: FencedBlockKind = "candidates";
export const FencedBlockMedia: FencedBlockKind = "media";
export const FencedBlockPermission: FencedBlockKind = "permission";
/**
 * FencedBlock is the v0.1 structured-output unit (D-19).
 * Daemon parses fence markers but never the Content body (D-20:
 * daemon-not-aware-of-skill). The browser dispatches on Kind.
 * Wire serialization (informational):
 * 	```<Kind>:<Skill>
 * 	{...content json...}
 * 	```
 */
export interface FencedBlock {
  kind: FencedBlockKind;
  skill: string; // skill id that emitted this block
  content: string; // skill-defined JSON body (opaque to daemon)
  blockId?: string; // optional, for action callbacks
}
/**
 * ProviderListResponse is the response body for GET /api/v1/providers.
 */
export interface ProviderListResponse {
  providers: string[];
}
/**
 * VersionResponse is the response body for GET /api/v1/version.
 * The UI reads its version from here rather than from a constant of its own.
 * The SPA is embedded in this binary, so the daemon's version IS the UI's
 * version — and asking for it makes the two structurally incapable of
 * disagreeing. A frontend-side literal had already drifted (the UI claimed
 * v0.5.0 while the binary reported v0.5.1-…), which is the same failure as
 * tether#67: a version string that reads like an authority but is wired to
 * nothing.
 */
export interface VersionResponse {
  version: string;
}
/**
 * ClientFrameKind is the discriminator for client→server frames sent on
 * the /wt/control bidi stream.
 */
export type ClientFrameKind = string;
export const ClientFramePing: ClientFrameKind = "ping";
export const ClientFrameAction: ClientFrameKind = "action";
export const ClientFrameResize: ClientFrameKind = "resize";
/**
 * ClientFrame is a client→server message on /wt/control. Kind selects the
 * interpretation of the remaining fields: "ping" carries only TS (RTT
 * probe); "action" carries SessionID/BlockID/Action/Skill — a fenced-block
 * callback (D-19 §5) routed to the named session (tether#8 T8); "resize"
 * carries SessionID/Cols/Rows and retargets that session's PTY (tether#68).
 * The /wt/control channel is not otherwise session-scoped, so SessionID is
 * the only way the daemon knows which session a frame targets.
 * Resize rides here rather than on /wt/shell because that stream is raw PTY
 * bytes by contract (D-05a §2 fact 4) — there is no field to put a size in
 * without introducing framing on the hot path.
 */
export interface ClientFrame {
  kind: ClientFrameKind;
  ts?: number /* int64 */;
  sessionId?: string;
  blockId?: string;
  action?: string;
  skill?: string;
  cols?: number /* uint16 */;
  rows?: number /* uint16 */;
}
/**
 * ControlFrame is a server→client message on /wt/control.
 */
export interface ControlFrame {
  kind: string;
  ts?: number /* int64 */;
}
/**
 * ControlPong is the ControlFrame.Kind sent in reply to a ClientFramePing.
 */
export const ControlPong = "pong";

//////////
// source: work.go

/**
 * WorkProject is the curated project descriptor for GET /api/v1/work/projects.
 */
export interface WorkProject {
  name: string;
}
/**
 * WorkReadyItem is a work item in the items/needsHumanSession/unclassified
 * segments of WorkQueue.
 */
export interface WorkReadyItem {
  id: string;
  slug: string;
  wiType?: string;
  priority: string;
  goal: string;
  unblockedAt?: string;
  createdAt?: string;
}
/**
 * WorkRunningItem is a work item in the running/staleRunning segment of
 * WorkQueue.
 */
export interface WorkRunningItem {
  id: string;
  slug: string;
  goal: string;
  ownerDisplay: string;
  lastActiveAt: string;
}
/**
 * WorkStalledItem is a work item in the stalled segment of WorkQueue.
 */
export interface WorkStalledItem {
  id: string;
  slug: string;
  stallReason: string;
  stalledSince: string;
  lastActorDisplay: string;
}
/**
 * WorkPausedItem is a work item in the paused segment of WorkQueue.
 */
export interface WorkPausedItem {
  id: string;
  slug: string;
  pausedSince: string;
  lastActorDisplay: string;
  pauseReason?: string;
}
/**
 * WorkQueue is the curated LCRS ready-queue response for
 * GET /api/v1/work/queue.
 */
export interface WorkQueue {
  items: WorkReadyItem[];
  running: WorkRunningItem[];
  stalled: WorkStalledItem[];
  paused: WorkPausedItem[];
  needsHumanSession: WorkReadyItem[];
  unclassified: WorkReadyItem[];
  staleRunning?: WorkRunningItem[];
}
/**
 * WorkItemDetail merges the whitelisted work_item fields with the current
 * step-machine state, for GET /api/v1/work/items/{id}.
 */
export interface WorkItemDetail {
  id: string;
  slug: string;
  goal: string;
  status: string;
  priority: string;
  wiType?: string;
  labels: string[];
  content?: string;
  currentStep?: string;
  currentStepStatus: string;
}
/**
 * WorkEvent mirrors one agent_events row for
 * GET /api/v1/work/items/{id}/events.
 */
export interface WorkEvent {
  ts: string;
  type: string;
  payload?: unknown;
}
/**
 * WorkEvents is the paginated event page returned by
 * GET /api/v1/work/items/{id}/events.
 */
export interface WorkEvents {
  events: WorkEvent[];
  nextCursor?: string;
}
/**
 * WorkRecentItem is a terminal (wrapped/cancelled) work item in the
 * done/recent history list for GET /api/v1/work/recent.
 */
export interface WorkRecentItem {
  id: string;
  slug: string;
  goal: string;
  status: string;
  priority: string;
  wiType?: string;
  closedAt?: string;
}
/**
 * WorkRecent is the curated done/recent history response for
 * GET /api/v1/work/recent (terminal work items). aihub currently returns these
 * in created-order (no closed_at sort param upstream), so the SPA re-sorts by
 * closedAt for display; a server-side closed_at ordering is a tracked aihub
 * follow-up.
 */
export interface WorkRecent {
  items: WorkRecentItem[];
}
/**
 * WorkGraphNode is a single work item node in the dependency/parent graph for
 * GET /api/v1/work/graph.
 */
export interface WorkGraphNode {
  id: string;
  slug: string;
  goal: string;
  status: string;
  priority: string;
  wiType?: string;
  parent?: string;
}
/**
 * WorkGraph is the curated response for GET /api/v1/work/graph.
 */
export interface WorkGraph {
  nodes: WorkGraphNode[];
}
/**
 * WorkDepEntry is one dependency edge for
 * GET /api/v1/work/items/{id}/dependencies.
 */
export interface WorkDepEntry {
  id: string;
  slug: string;
  project: string;
  kind: string;
  note: string;
}
/**
 * WorkDependencies is the curated response for
 * GET /api/v1/work/items/{id}/dependencies.
 */
export interface WorkDependencies {
  blocking: WorkDepEntry[];
  blockedBy: WorkDepEntry[];
}
/**
 * WorkStepNode is a single step-graph node for
 * GET /api/v1/work/items/{id}/steps, annotated with its progress status.
 * Status is one of "done", "current", or "pending".
 */
export interface WorkStepNode {
  id: string;
  status: string;
  prev?: string[];
}
/**
 * WorkSteps is the curated response for GET /api/v1/work/items/{id}/steps.
 * Degraded is true when no scenario graph file could be resolved for the
 * work item (e.g. no matching .repo/<repo>/<wiType>[.<project>].md), in
 * which case Nodes is synthesized best-effort from step-completion events
 * without Prev edges.
 */
export interface WorkSteps {
  nodes: WorkStepNode[];
  degraded: boolean;
}
