// Code generated by tygo. DO NOT EDIT.
// ⚠ AUTO-GENERATED FROM internal/wire/types.go BY tygo. DO NOT EDIT.
// To change shape: edit Go source then `make codegen`.

//////////
// source: format.go

/**
 * HashHex64 is the canonical wire format for SHA-256 fingerprints:
 * 64 lowercase hex characters, no separators, no prefix.
 * Browser parser regex: ^[0-9a-f]{64}$
 * Accepted:   "4c55656033cc29b05037294b2c1bdd2c294963b57b9238a2a758aec8d87eb288"
 * Rejected:   "4c:55:65:..." (colons), "4C55..." (uppercase), "0x4c55..." (prefix)
 * Both /cert-hash (DER) and /cert-hash-spki (SPKI) return values of this type.
 * Validated by wire-contract.spec.ts contract K.7.1 / D-22 §6 #1.
 */
export type HashHex64 = string;
/**
 * SessionID is the stable identifier for a cc-managed JSONL session,
 * as returned in the system/init stream-json event (D-05a §3).
 * Opaque string; format is cc-internal and subject to change.
 */
export type SessionID = string;

//////////
// source: types.go

/**
 * EnvelopeKind is the discriminator field on every wire envelope.
 * The browser dispatches on this value to route to the correct handler.
 * Additional kinds are added in s4+ as channels are implemented.
 */
export type EnvelopeKind = string;
export const KindMessage: EnvelopeKind = "message"; // assistant text / tool output (s4)
export const KindPermission: EnvelopeKind = "permission"; // PreToolUse callback (s5)
export const KindFenced: EnvelopeKind = "fenced"; // D-19 fenced-block structured output (s4)
export const KindError: EnvelopeKind = "error"; // daemon-side error surfaced to UI
export const KindResult: EnvelopeKind = "result"; // turn complete; payload is stop reason string
/**
 * Envelope is the top-level wrapper for all events sent over /wt/events
 * and /wt/chat. The Payload field carries kind-specific JSON (D-05a §3,
 * D-05b §3.1, D-19). Routing table per §10.B.4 is implemented in s4.
 */
export interface Envelope {
  kind: EnvelopeKind;
  sessionId?: SessionID;
  payload?: any;
}
/**
 * FencedBlockKind is the discriminator for D-19 fenced-block protocol.
 * v0.1 defines 5 kinds; more may be added in v1.0+.
 */
export type FencedBlockKind = string;
export const FencedBlockDag: FencedBlockKind = "dag";
export const FencedBlockForm: FencedBlockKind = "form";
export const FencedBlockCandidates: FencedBlockKind = "candidates";
export const FencedBlockMedia: FencedBlockKind = "media";
export const FencedBlockPermission: FencedBlockKind = "permission";
/**
 * FencedBlock is the v0.1 structured-output unit (D-19).
 * Daemon parses fence markers but never the Content body (D-20:
 * daemon-not-aware-of-skill). The browser dispatches on Kind.
 * Wire serialization (informational):
 * 	```<Kind>:<Skill>
 * 	{...content json...}
 * 	```
 */
export interface FencedBlock {
  kind: FencedBlockKind;
  skill: string; // skill id that emitted this block
  content: string; // skill-defined JSON body (opaque to daemon)
  blockId?: string; // optional, for action callbacks
}
/**
 * ProviderListResponse is the response body for GET /api/v1/providers.
 */
export interface ProviderListResponse {
  providers: string[];
}
/**
 * ClientFrameKind is the discriminator for client→server frames sent on
 * the /wt/control bidi stream.
 */
export type ClientFrameKind = string;
export const ClientFramePing: ClientFrameKind = "ping";
export const ClientFrameAction: ClientFrameKind = "action";
/**
 * ClientFrame is a client→server message on /wt/control. Kind selects the
 * interpretation of the remaining fields: "ping" carries only TS (RTT
 * probe); "action" carries SessionID/BlockID/Action/Skill — a fenced-block
 * callback (D-19 §5) routed to the named session (tether#8 T8). The
 * /wt/control channel is not otherwise session-scoped, so SessionID is the
 * only way the daemon knows which session an action targets.
 */
export interface ClientFrame {
  kind: ClientFrameKind;
  ts?: number /* int64 */;
  sessionId?: string;
  blockId?: string;
  action?: string;
  skill?: string;
}
/**
 * ControlFrame is a server→client message on /wt/control.
 */
export interface ControlFrame {
  kind: string;
  ts?: number /* int64 */;
}
/**
 * ControlPong is the ControlFrame.Kind sent in reply to a ClientFramePing.
 */
export const ControlPong = "pong";

//////////
// source: work.go

/**
 * WorkProject is the curated project descriptor for GET /api/v1/work/projects.
 */
export interface WorkProject {
  name: string;
}
/**
 * WorkReadyItem is a work item in the items/needsHumanSession/unclassified
 * segments of WorkQueue.
 */
export interface WorkReadyItem {
  id: string;
  slug: string;
  wiType?: string;
  priority: string;
  goal: string;
  unblockedAt?: string;
  createdAt?: string;
}
/**
 * WorkRunningItem is a work item in the running/staleRunning segment of
 * WorkQueue.
 */
export interface WorkRunningItem {
  id: string;
  slug: string;
  goal: string;
  ownerDisplay: string;
  lastActiveAt: string;
}
/**
 * WorkStalledItem is a work item in the stalled segment of WorkQueue.
 */
export interface WorkStalledItem {
  id: string;
  slug: string;
  stallReason: string;
  stalledSince: string;
  lastActorDisplay: string;
}
/**
 * WorkPausedItem is a work item in the paused segment of WorkQueue.
 */
export interface WorkPausedItem {
  id: string;
  slug: string;
  pausedSince: string;
  lastActorDisplay: string;
  pauseReason?: string;
}
/**
 * WorkQueue is the curated LCRS ready-queue response for
 * GET /api/v1/work/queue.
 */
export interface WorkQueue {
  items: WorkReadyItem[];
  running: WorkRunningItem[];
  stalled: WorkStalledItem[];
  paused: WorkPausedItem[];
  needsHumanSession: WorkReadyItem[];
  unclassified: WorkReadyItem[];
  staleRunning?: WorkRunningItem[];
}
/**
 * WorkItemDetail merges the whitelisted work_item fields with the current
 * step-machine state, for GET /api/v1/work/items/{id}.
 */
export interface WorkItemDetail {
  id: string;
  slug: string;
  goal: string;
  status: string;
  priority: string;
  wiType?: string;
  labels: string[];
  content?: string;
  currentStep?: string;
  currentStepStatus: string;
}
/**
 * WorkEvent mirrors one agent_events row for
 * GET /api/v1/work/items/{id}/events.
 */
export interface WorkEvent {
  ts: string;
  type: string;
  payload?: unknown;
}
/**
 * WorkEvents is the paginated event page returned by
 * GET /api/v1/work/items/{id}/events.
 */
export interface WorkEvents {
  events: WorkEvent[];
  nextCursor?: string;
}
/**
 * WorkRecentItem is a terminal (wrapped/cancelled) work item in the
 * done/recent history list for GET /api/v1/work/recent.
 */
export interface WorkRecentItem {
  id: string;
  slug: string;
  goal: string;
  status: string;
  priority: string;
  wiType?: string;
  closedAt?: string;
}
/**
 * WorkRecent is the curated done/recent history response for
 * GET /api/v1/work/recent (terminal work items). aihub currently returns these
 * in created-order (no closed_at sort param upstream), so the SPA re-sorts by
 * closedAt for display; a server-side closed_at ordering is a tracked aihub
 * follow-up.
 */
export interface WorkRecent {
  items: WorkRecentItem[];
}
/**
 * WorkGraphNode is a single work item node in the dependency/parent graph for
 * GET /api/v1/work/graph.
 */
export interface WorkGraphNode {
  id: string;
  slug: string;
  goal: string;
  status: string;
  priority: string;
  wiType?: string;
  parent?: string;
}
/**
 * WorkGraph is the curated response for GET /api/v1/work/graph.
 */
export interface WorkGraph {
  nodes: WorkGraphNode[];
}
/**
 * WorkDepEntry is one dependency edge for
 * GET /api/v1/work/items/{id}/dependencies.
 */
export interface WorkDepEntry {
  id: string;
  slug: string;
  project: string;
  kind: string;
  note: string;
}
/**
 * WorkDependencies is the curated response for
 * GET /api/v1/work/items/{id}/dependencies.
 */
export interface WorkDependencies {
  blocking: WorkDepEntry[];
  blockedBy: WorkDepEntry[];
}
/**
 * WorkStepNode is a single step-graph node for
 * GET /api/v1/work/items/{id}/steps, annotated with its progress status.
 * Status is one of "done", "current", or "pending".
 */
export interface WorkStepNode {
  id: string;
  status: string;
  prev?: string[];
}
/**
 * WorkSteps is the curated response for GET /api/v1/work/items/{id}/steps.
 * Degraded is true when no scenario graph file could be resolved for the
 * work item (e.g. no matching .repo/<repo>/<wiType>[.<project>].md), in
 * which case Nodes is synthesized best-effort from step-completion events
 * without Prev edges.
 */
export interface WorkSteps {
  nodes: WorkStepNode[];
  degraded: boolean;
}
