// Code generated by tygo. DO NOT EDIT.
// ⚠ AUTO-GENERATED FROM internal/wire/types.go BY tygo. DO NOT EDIT.
// To change shape: edit Go source then `make codegen`.

//////////
// source: format.go

/**
 * HashHex64 is the canonical wire format for SHA-256 fingerprints:
 * 64 lowercase hex characters, no separators, no prefix.
 * Browser parser regex: ^[0-9a-f]{64}$
 * Accepted:   "4c55656033cc29b05037294b2c1bdd2c294963b57b9238a2a758aec8d87eb288"
 * Rejected:   "4c:55:65:..." (colons), "4C55..." (uppercase), "0x4c55..." (prefix)
 * Both /cert-hash (DER) and /cert-hash-spki (SPKI) return values of this type.
 * Validated by wire-contract.spec.ts contract K.7.1 / D-22 §6 #1.
 */
export type HashHex64 = string;
/**
 * SessionID is the stable identifier for a cc-managed JSONL session,
 * as returned in the system/init stream-json event (D-05a §3).
 * Opaque string; format is cc-internal and subject to change.
 */
export type SessionID = string;

//////////
// source: types.go

/**
 * EnvelopeKind is the discriminator field on every wire envelope.
 * The browser dispatches on this value to route to the correct handler.
 * Additional kinds are added in s4+ as channels are implemented.
 */
export type EnvelopeKind = string;
export const KindMessage: EnvelopeKind = "message"; // assistant text / tool output (s4)
export const KindPermission: EnvelopeKind = "permission"; // PreToolUse callback (s5)
export const KindFenced: EnvelopeKind = "fenced"; // D-19 fenced-block structured output (s4)
export const KindError: EnvelopeKind = "error"; // daemon-side error surfaced to UI
/**
 * Envelope is the top-level wrapper for all events sent over /wt/events
 * and /wt/chat. The Payload field carries kind-specific JSON (D-05a §3,
 * D-05b §3.1, D-19). Routing table per §10.B.4 is implemented in s4.
 */
export interface Envelope {
  kind: EnvelopeKind;
  sessionId?: SessionID;
  payload?: any;
}
/**
 * FencedBlockKind is the discriminator for D-19 fenced-block protocol.
 * v0.1 defines 5 kinds; more may be added in v1.0+.
 */
export type FencedBlockKind = string;
export const FencedBlockDag: FencedBlockKind = "dag";
export const FencedBlockForm: FencedBlockKind = "form";
export const FencedBlockCandidates: FencedBlockKind = "candidates";
export const FencedBlockMedia: FencedBlockKind = "media";
export const FencedBlockPermission: FencedBlockKind = "permission";
/**
 * FencedBlock is the v0.1 structured-output unit (D-19).
 * Daemon parses fence markers but never the Content body (D-20:
 * daemon-not-aware-of-skill). The browser dispatches on Kind.
 * Wire serialization (informational):
 * 	```<Kind>:<Skill>
 * 	{...content json...}
 * 	```
 */
export interface FencedBlock {
  kind: FencedBlockKind;
  skill: string; // skill id that emitted this block
  content: string; // skill-defined JSON body (opaque to daemon)
  blockId?: string; // optional, for action callbacks
}
/**
 * ProviderListResponse is the response body for GET /api/v1/providers.
 */
export interface ProviderListResponse {
  providers: string[];
}
