// Code generated by tygo. DO NOT EDIT.
// ⚠ AUTO-GENERATED FROM wire/types.go BY tygo. DO NOT EDIT.
// To change shape: edit Go source then `go generate ./wire`.

//////////
// source: types.go
/*
Package wire defines the shared schema between the Go server and the
TypeScript browser frontend. tygo generates a 1:1 TS file from this
package; both sides import the same interface shape.

Format conventions that types alone CAN'T express (e.g., hash with no
colons, echo without prefix) are documented per-type in godoc and
validated by web/test/wire-contract.spec.ts in CI.
*/

/**
 * HashHex64 is the canonical wire format for SHA-256 fingerprints:
 * **64 lowercase hex characters, no separators**.
 * Example:
 * 	"4c55656033cc29b05037294b2c1bdd2c294963b57b9238a2a758aec8d87eb288"
 * NOT acceptable on the wire (verified by contract test):
 *   - colon separated: "4c:55:65:..."
 *   - uppercase: "4C55..."
 *   - 0x prefix: "0x4c55..."
 * Both /cert-hash and /cert-hash-spki return values of this format.
 * Browser parser regex: /^[0-9a-f]{64}$/
 */
export type HashHex64 = string;
/**
 * CertHashes is the response body of the (currently text-only) cert
 * fingerprint endpoints. Reserved for future JSON migration.
 */
export interface CertHashes {
  der: HashHex64;
  spki: HashHex64;
}
/**
 * EchoTestPayload is the message shape used by the WT bidi-stream echo
 * test in step3_browser/index.html.
 * **Wire contract:** server returns the input bytes verbatim — no
 * prefix, no transformation, no extra framing. Verified by browser
 * test "bidi echo".
 */
export interface EchoTestPayload {
  text: string;
}
/**
 * FencedBlockKind is the discriminator for D-19 fenced-block protocol.
 * Reserved enumeration; v0.1 lists 4 kinds, more in v1.0+.
 */
export type FencedBlockKind = string;
export const FencedBlockDag: FencedBlockKind = "dag";
export const FencedBlockForm: FencedBlockKind = "form";
export const FencedBlockCandidates: FencedBlockKind = "candidates";
export const FencedBlockMedia: FencedBlockKind = "media";
/**
 * FencedBlock is the v0.1 1st-class structured-output unit (per D-19).
 * Wire format (informational; serialized as JSON):
 * 	```<Kind>:<Skill>
 * 	{...content json...}
 * 	```
 * daemon parses fence markers but never the content body (per D-20:
 * daemon-not-aware-of-skill).
 */
export interface FencedBlock {
  kind: FencedBlockKind;
  skill: string; // skill id that emitted this block
  content: string; // skill-defined JSON body
  blockId?: string; // optional, for action callbacks
}
